### ISSUE TITLE
Analytics version-dependent?

### ISSUE THREAD

**Issue by thompsonpaul** [ronalfy/wordpress-gravity-forms-event-tracking#10]
Love what you've put together here, Nathan. This is one of the ridiculously glaring gaps in an otherwise terrific forms system.

I couldn't tell by scanning the code - since you're utilising the Measurement Protocol, does this mean it doesn't matter whether a site is using Classic or Universal tracking snippet? i.e. will it work without issue regardless of which version of the tracking snippet is being utilised?

Either way, I'd suggest the status of this requirement be added to the Requirements documentation for clarity and to save you more questions like this one :)

**Comment by nathanmarks** [comment]
Hey @thompsonpaul , thanks! Yeah GF really needed this. I originally used a JS implementation (not measurement protocol) when I first wrote the plugin but it struggled with a number of GF use cases and this is a much more robust solution.

The measurement protocol is part of universal analytics so the GA account itself must not be classic. People should upgrade anyways!

But yes I should put that in the requirements too.
