### ISSUE TITLE
Issue regarding Event Value

### ISSUE THREAD

**Issue by enlatis** [ronalfy/wordpress-gravity-forms-event-tracking#13]
It seems it's only tracking the event value on payment forms, but is there a way to easily modify it to put in your own event value? Seems like it should be easy to pass through a custom value via a merge tag.

**Comment by nathanmarks** [comment]
@enlatis Thanks for this, it is definitely a bug and I'll get it patched this week!

**Comment by nathanmarks** [comment]
Will release a hotfix with this in shortly. Patched it in my development branch.

**Comment by nathanmarks** [comment]
1.6.2 contains this fix. Please let me know if you still have any issues.

**Comment by enlatis** [comment]
Hey Nathan,

It still doesn't seem to be working. I'm using a gravity forms merge field for the value, would that have anything to do with it? IE. {Total:132}.

Any thoughts?

**Comment by nathanmarks** [comment]
Hey @enlatis , there definitely was a bug using merge fields for the value as I was not converting it to a number correctly from the formatted amount returned by the merge tag. 

Here's what my example form is pushing to google, seems to be working:
http://glui.me/?i=cuv8qqwgzzqx9at/2015-02-10_at_6.47_PM.png/

and the setup:
http://glui.me/?i=y5b2kmbslai6znf/2015-02-10_at_6.48_PM.png/

**Comment by enlatis** [comment]
Okay, so 1.6.2 fixed it? Or did you have to fix it again?

**Comment by nathanmarks** [comment]
@enlatis 1.6.2 had the fix. Are you seeing the conversions come through in analytics? 

Here's 2 conversions from that form:

http://glui.me/?i=4gndg8x1f5nn6bd/2015-02-10_at_7.04_PM.png/

**Comment by enlatis** [comment]
Okay, yeah, I'm seeing one come through, but I had another order that day
too, and it isn't showing up. I'll wait to see tomorrow to see if anything
more shows up.

**Comment by nathanmarks** [comment]
@enlatis When you make an order do you see the event come through in real-time analytics?

It's pretty much impossible for it to work sometimes and not other times unless there is something else affecting it on the WP side or the connection to google when sending the data.

**Comment by nathanmarks** [comment]
@enlatis Also are you using a payment gateway with this? If so, which one?

**Comment by enlatis** [comment]
Hey Nathan,

I'm using Freshbooks with this. My IP address is filtered out. I'll update
you tomorrow.
