### ISSUE TITLE
Feature Request: Disable events for user roles

### ISSUE THREAD

**Issue by intelliweb** [ronalfy/wordpress-gravity-forms-event-tracking#14]
It would be great to have an option to "turn off" events for logged in users or by user role so that when admin/staff are testing forms the events are not included in Google Analytics.

Yes, we can filter IP addresses in Google Analytics but that gets messy when there are other people doing testing and with non-static IPs.

A setting for this could be useful, but for now I'll settle for a hook that could be used to prevent events from being triggered under certain circumstances (e.g. user is logged in).  The only current hook I see that might work is:

    gform_ua_id

@nathanmarks thoughts?
Could we add an action/filter somewhere to facilitate this?

**Comment by nathanmarks** [comment]
Definitely, will try squeeze this in very soon.

**Comment by nathanmarks** [comment]
@intelliweb Actually, try just removing this filter:

`add_filter( 'gform_after_submission', array( $this, 'maybe_process_feed' ), 10, 2 );`

**Comment by nathanmarks** [comment]
**edit** realised my last reply was actually incorrect. Will add this before the next update though.

**Comment by nathanmarks** [comment]
Actually, without any changes you should be able to do this (with some of your own logic inside the function of course).

```
function disable_event_tracking() {
	remove_filter( 'gform_after_submission', array( Gravity_Forms_Event_Tracking::get_instance(), 'maybe_process_feed' ) );
}
add_action( 'init', 'disable_event_tracking', 20 );
```

**Comment by intelliweb** [comment]
Would that affect other Gravity Forms feed-based add-ons?
