### ISSUE TITLE
Goal Completion Location is always (entrance)

### ISSUE THREAD

**Issue by kimmcc** [ronalfy/wordpress-gravity-forms-event-tracking#18]
Hi Nathan,

I upgraded from classic to Universal GA, hoping that would fix the following issues: all contact form goal completions showing as medium: direct, locations showing as (entrance). Now, medium: organic is being reported properly, but all my tests still show (entrance) as goal completion location. 

Some notes, in case any of the following helps troubleshoot: I'm not having this issue with goals that don't use this plugin (i.e. click-to-call event tracking); the forms I'm tracking are on pages using https 302 redirected from http; theme and plugins are all up-to-date; event tracking feed is toggled on; I am using the same feed name 'Event Tracking Feed' for two separate forms.

Gravity Forms 1.9.5
Gravity Forms Google Analytics Event Tracking 1.6.3
Wordpress 4.1.1

If I can make this work, it will be immensely useful on multiple sites that I manage.

Thanks for your help.

Kim

**Comment by fktc** [comment]
Hi Kim, hi Nathan,

FYI this issue occurs in my environment as well.Everything up to date and the forms are standard (i.e. no multipage, not on redirected pages). All Goal Completion Locations are set to (entrance) and all source/medium values are set to (direct) / (none).

I have Gravity Forms MailcChimp add-on and Gravity Forms PayPal Standard add-on activated on the WordPress installation, maybe this is causing the issue?

In any case, thanks for your help.

**Comment by kimmcc** [comment]
Hi,

It seems updating the site's Analytics yo Universal has solved the (direct) / (none) issue for me. Have you tried that? Though, I'm aware it's only a partial solution. 

Kim

**Comment by nathanmarks** [comment]
@kimmcc , @fktc 

Thanks for bringing this up guys. I'll take a look. Also the measurement protocol used to be UA only -- did google change that?

**Comment by fktc** [comment]
Hey @nathanmarks 

I have UA enabled but still no luck. It counts the goals but nothing else. Here are a few screenshots FYI
http://cl.ly/image/1T0g1t080L1m
http://cl.ly/image/2r3M2s0K2x1U
http://cl.ly/image/2o3j171w2J3P

If I can do anything to help troubleshooting this, please let me know...

**Comment by franklepkowski** [comment]
Hey @nathanmarks 

I'm experiencing the same problem. I'm on UA, we use a private vendor for email marketing that enables Google Analytics tracking. I'm trying to see how effective email marketing is versus other channels. So far all Gravity Forms conversions are being categorized (direct)/(not set). 

GA picks up event submissions just fine and properly detects the email/subject line for traffic source. It's attributing the event to the email traffic source that's not happening. Currently all conversions are treated as (not set), even if I have GA tracking info in the URL:
![screen shot 2015-04-22 at 1 42 23 pm](https://cloud.githubusercontent.com/assets/12072064/7283159/a72ab9ac-e902-11e4-9486-1e7c8dee1615.png)

I'm also getting the following error message from GA:
![screen shot 2015-04-22 at 1 51 10 pm](https://cloud.githubusercontent.com/assets/12072064/7283190/f2bef086-e902-11e4-91f6-e7560a79fe30.png)
I have the correct UA tracking code on the page, and this code runs before the event is fired in Gravity Forms. Hope this helps.

Let me know if anyone else has any tips for troubleshooting. Thanks!

**Comment by kimmcc** [comment]
Not sure if this is helpful for troubleshooting, but I got the following messages on a different site while updating the plugin:

first this: 

An error occurred while updating Gravity Forms Google Analytics Event Tracking:
Could not copy file. gravity-forms-google-analytics-event-tracking/includes/vendor/ga-mp/src/Racecore/GATracking/Exception/MissingConfigurationException.php (during a bulk plugin update)

then this:

Could not copy file. gravity-forms-google-analytics-event-tracking/includes/vendor/ga-mp/src/Racecore/GATracking/Exception/MissingTrackingParameterException.php (when I then tried  to update the plugin individually)

Hope this helps!
Kim

**Comment by nathanmarks** [comment]
Hey guys,

I just want you all to know that I've had a very busy month but intend on doing a slew of updates soon that should include fixing this. I am rewriting the plugin and a goal I have is to make sure I am sending all the parameters possible to GA.

**Comment by intelliweb** [comment]
@nathanmarks Any update on progress? I've run into an issue where ideally the hostname would be passed to GA.  That seems to be possible with the measurement protocol parameters: https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#dh

As background, this is related to referral spam in GA. I'm wanting to create a filter to exclude all bogus hostnames, but currently all Gravity Forms-based events have hostname: (not set) which complicates things.

**Comment by nathanmarks** [comment]
@intelliweb It's on the radar, I started a new job in March and have been super busy since but things are slowing down a bit now. I'm aiming to get to this in the next couple of weeks.

**Comment by rswong** [comment]
Hi @nathanmarks ,

This is an excellent plugin. Similar to people above I really wish we could have this feature enabled as it would be super useful to be able to attribute those events to the proper channel.

Just want to say that this plugin is superb. You should consider releasing this as a premium plugin. I think many people would be willing to pay for it.

**Comment by rswong** [comment]
@nathanmarks Hi Nathan, any update on the progress ? Been waiting for this very very eagerly.

**Comment by ronalfy** [comment]
@nathanmarks is no longer involved with this plugin. I'm still getting familiar with the code base, but pull requests are always welcome.

**Comment by ronalfy** [comment]
Hey guys/gals, I'm going to release version 1.7 today that will set the location of the goal completion. Please let me know if this version fixes your issues. I'm still getting a handle on GA (I'm far from an expert on it), but I'll do my best to pass as much data as I can.

**Comment by jazir5** [comment]
I am still having this issue, goal completions show up in analytics as "entrance"
