### ISSUE TITLE
Error: unexpected t_string line 171

### ISSUE THREAD

**Issue by kimmcc** [ronalfy/wordpress-gravity-forms-event-tracking#22]
I'm getting this error when I try to install and activate the plugin:

Parse error: syntax error, unexpected T_STRING in /home/content/84/10638984/html/wp-content/plugins/gravity-forms-google-analytics-event-tracking/includes/class-gravity-forms-event-tracking-feed.php on line 171

Could it be an incompatibility with WP 4.2.3?

**Comment by ronalfy** [comment]
Make sure you are running PHP 5.3 and greater.
