### ISSUE TITLE
This add-on needs to be updated. Please contact the developer.

### ISSUE THREAD

**Issue by ronalfy** [ronalfy/wordpress-gravity-forms-event-tracking#23]
Just a heads up, this is showing up in Gravity Forms now.
![gagravity](https://cloud.githubusercontent.com/assets/636521/9611925/418a2b38-50a8-11e5-9d74-7c7b6d0dc0de.jpg)

**Comment by nathanmarks** [comment]
@ronalfy I don't have time to work on this as I'm no longer really working with wordpress or even PHP that much. Do you want to take ownership of the repository?

**Comment by ronalfy** [comment]
Sure, can you add me on as an owner in the WordPress repo too if you don't mind?

**Comment by nathanmarks** [comment]
@ronalfy need you to remove your fork to xfer it

**Comment by ronalfy** [comment]
@nathanmarks fork removed. Thanks so much.
