### ISSUE TITLE
Notice fired when UA code is not yet set

### ISSUE THREAD

**Issue by mitch827** [ronalfy/wordpress-gravity-forms-event-tracking#25]
Hi @ronalfy ,

first thank you for updating and developing this plugin.

When I first installed on local dev environment the plugin, without entering the UA code, I got a notice fired by the debugger

`Undefined index: gravity_forms_event_tracking_ua in /Users/username/dev/www.website.dev/wp-content/plugins/gravity-forms-google-analytics-event-tracking/includes/class-gravity-forms-event-tracking-feed.php on line 150`

It would be enough to make a check if the UA code is not present.

Thanks!

**Comment by ronalfy** [comment]
I'm releasing version 1.7 today which will fix this notice and provide a better UX if a person hasn't entered a UA code in the settings page or on the feed page.

**Comment by mitch827** [comment]
yeah :+1:
