### ISSUE TITLE
Document compatibility and/or integration with Yoast's GA plugin?

### ISSUE THREAD

**Issue by lkraav** [ronalfy/wordpress-gravity-forms-event-tracking#6]
Great news seeing GF event tracking. First question popping up in my head was "how well is this going to get along with the big players". Yoast first, and however much time is left for the others. This issue is more of a discussion item really, but could end up as a README.md documentation patch or actual code implementation if interop is not there at the moment.

**Comment by hubdotcom** [comment]
I'm running with in parallel with Yoast's GA plugin and will report back the results.
I can't image there being any conflict - from my understanding, Yoast implements the front end JS for tracking page views and GF Event Tracking deals with PHP calls to GA purely for tracking events. Is that correct @nathanmarks?

**Comment by ronalfy** [comment]
At this point I don't want to rely on another plugin for GA data. This plugin already allows multiple GA codes in the feeds, and I plan on enabling this on the settings screen as well.
